['C3w', 'C2w', <Movement.Left: (0, -1)>]
['C3w', 'B2w', <Movement.DownLeft: (-1, -1)>]
['C3w', 'B3w', <Movement.DownRight: (-1, 0)>]
['C4w', 'B3w', <Movement.DownLeft: (-1, -1)>]
['C4w', 'B4w', <Movement.DownRight: (-1, 0)>]
['D3w', 'D2w', <Movement.Left: (0, -1)>]
['D3w', 'E3w', <Movement.UpLeft: (1, 0)>]
['D3w', 'C2w', <Movement.DownLeft: (-1, -1)>]
['D6w', 'D7w', <Movement.Right: (0, 1)>]
['D6w', 'C6w', <Movement.DownRight: (-1, 0)>]
['E7w', 'E8w', <Movement.Right: (0, 1)>]
['E7w', 'D7w', <Movement.DownRight: (-1, 0)>]
['F4w', 'F3w', <Movement.Left: (0, -1)>]
['F4w', 'G4w', <Movement.UpLeft: (1, 0)>]
['F4w', 'E3w', <Movement.DownLeft: (-1, -1)>]
['G5w', 'G4w', <Movement.Left: (0, -1)>]
['G5w', 'H5w', <Movement.UpLeft: (1, 0)>]
['G9w', 'F9w', <Movement.DownRight: (-1, 0)>]
['H7w', 'I7w', <Movement.UpLeft: (1, 0)>]
['H7w', 'I8w', <Movement.UpRight: (1, 1)>]
['H8w', 'I8w', <Movement.UpLeft: (1, 0)>]
['H8w', 'I9w', <Movement.UpRight: (1, 1)>]
['H9w', 'I9w', <Movement.UpLeft: (1, 0)>]
[['C3w', 'C4w'], ['C2w', 'C3w'], <Movement.Left: (0, -1)>]
[['C3w', 'C4w'], ['B2w', 'B3w'], <Movement.DownLeft: (-1, -1)>]
[['C3w', 'C4w'], ['B3w', 'B4w'], <Movement.DownRight: (-1, 0)>]
[['C3w', 'D3w'], ['C2w', 'D2w'], <Movement.Left: (0, -1)>]
[['C3w', 'D3w'], ['D3w', 'E3w'], <Movement.UpLeft: (1, 0)>]
[['C3w', 'D3w'], ['B2w', 'C2w'], <Movement.DownLeft: (-1, -1)>]
[['C3w', 'D3w'], ['B3w', 'C3w'], <Movement.DownRight: (-1, 0)>]
[['C3w', 'D4w'], ['B2w', 'C3w'], <Movement.DownLeft: (-1, -1)>]
[['C4w', 'D4w'], ['B4w', 'C4w'], <Movement.DownRight: (-1, 0)>]
[['D3w', 'D4w'], ['D2w', 'D3w'], <Movement.Left: (0, -1)>]
[['D6w', 'E7w'], ['D7w', 'E8w'], <Movement.Right: (0, 1)>]
[['D6w', 'E7w'], ['C6w', 'D7w'], <Movement.DownRight: (-1, 0)>]
[['F4w', 'G5w'], ['F3w', 'G4w'], <Movement.Left: (0, -1)>]
[['F4w', 'G5w'], ['G4w', 'H5w'], <Movement.UpLeft: (1, 0)>]
[['F4w', 'G5w'], ['E3w', 'F4w'], <Movement.DownLeft: (-1, -1)>]
[['G7w', 'H7w'], ['H7w', 'I7w'], <Movement.UpLeft: (1, 0)>]
[['G7w', 'H8w'], ['H8w', 'I9w'], <Movement.UpRight: (1, 1)>]
[['G8w', 'H8w'], ['H8w', 'I8w'], <Movement.UpLeft: (1, 0)>]
[['G9w', 'H9w'], ['H9w', 'I9w'], <Movement.UpLeft: (1, 0)>]
[['G9w', 'H9w'], ['F9w', 'G9w'], <Movement.DownRight: (-1, 0)>]
[['H7w', 'H8w'], ['I7w', 'I8w'], <Movement.UpLeft: (1, 0)>]
[['H7w', 'H8w'], ['I8w', 'I9w'], <Movement.UpRight: (1, 1)>]
[['H8w', 'H9w'], ['I8w', 'I9w'], <Movement.UpLeft: (1, 0)>]
[['C3b', 'C4b'], ['C4b', 'C5b'], <Movement.Right: (0, 1)>]
[['D6b', 'E7b'], ['C5b', 'D6b'], <Movement.DownLeft: (-1, -1)>]
[['F4b', 'G5b'], ['G5b', 'H6b'], <Movement.UpRight: (1, 1)>]
[['G8b', 'H8b'], ['F8b', 'G8b'], <Movement.DownRight: (-1, 0)>]
[['H7b', 'H8b'], ['H6b', 'H7b'], <Movement.Left: (0, -1)>]
[['H7b', 'H8b', 'H9b'], ['I7b', 'I8b', 'I9b'], <Movement.UpLeft: (1, 0)>]
[['H7w', 'H8w', 'H9w'], ['H6w', 'H7w', 'H8w'], <Movement.Left: (0, -1)>]
